# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:

print("NumPy Version:", np.__version__)
print("NumPy Configuration:")
print(np.show_config())


NumPy Version: 1.23.5
NumPy Configuration:
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language =

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
null_vector = np.zeros(10)
print(null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
import numpy as np
my_array = np.zeros((3, 4), dtype=np.int32)
memory_size = my_array.nbytes
print(f"Memory size of the array: {memory_size} bytes")


Memory size of the array: 48 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:

help(np.add)



Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
import numpy as np
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:

my_vector = np.arange(10, 50)

print(my_vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
import numpy as np
my_vector = np.array([1, 2, 3, 4, 5])
reversed_vector = my_vector[::-1]
print(reversed_vector)


[5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
import numpy as np
my_array = np.arange(9)
my_matrix = my_array.reshape((3, 3))
print(my_matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
import numpy as np
my_array = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(my_array)
print(nonzero_indices)


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
import numpy as np
random_array = np.random.rand(3, 3, 3)
print(random_array)


[[[0.66568457 0.83512954 0.5164403 ]
  [0.65111424 0.36726146 0.37875567]
  [0.48459686 0.13533537 0.00178544]]

 [[0.05985312 0.10888535 0.14872798]
  [0.74356744 0.83108758 0.0042429 ]
  [0.07156614 0.13468377 0.58985537]]

 [[0.27227072 0.08344828 0.31010561]
  [0.11942661 0.68086088 0.5089555 ]
  [0.14701193 0.7382046  0.09760529]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
import numpy as np
random_array = np.random.rand(10, 10)
min_value = np.min(random_array)
max_value = np.max(random_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)


Minimum value: 0.02487374014604493
Maximum value: 0.9890852502628111


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
import numpy as np
random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)
print("Random Vector:", random_vector)
print("Mean Value:", mean_value)


Random Vector: [0.09853549 0.64661863 0.27030234 0.82299602 0.61124359 0.66326361
 0.27252799 0.22597726 0.97942409 0.21669767 0.32547017 0.50779452
 0.43814477 0.68710166 0.50073871 0.84478262 0.59943808 0.56481366
 0.84155904 0.86408635 0.02046891 0.78730475 0.87737622 0.50727366
 0.4450959  0.00916001 0.26882391 0.12425517 0.86371179 0.75679605]
Mean Value: 0.5213927543580508


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
import numpy as np
rows, columns = 5, 5
array_2d = np.ones((rows, columns))
array_2d[1:-1, 1:-1] = 0
print(array_2d)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
import numpy as np
existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])
rows, columns = existing_array.shape
new_array = np.zeros((rows + 2, columns + 2))
new_array[1:-1, 1:-1] = existing_array
print("Existing Array:")
print(existing_array)
print("\nArray with Border:")
print(new_array)


Existing Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array with Border:
[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 0.]
 [0. 4. 5. 6. 0.]
 [0. 7. 8. 9. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [20]:
import numpy as np

result1 = 0 * np.nan
result2 = np.nan == np.nan
result3 = np.inf > np.nan
result4 = np.nan - np.nan
result5 = np.nan in set([np.nan])
result6 = 0.3 == 3 * 0.1

print("Result 1:", result1)
print("Result 2:", result2)
print("Result 3:", result3)
print("Result 4:", result4)
print("Result 5:", result5)
print("Result 6:", result6)


Result 1: nan
Result 2: False
Result 3: False
Result 4: nan
Result 5: True
Result 6: False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [22]:
import numpy as np
values_below_diagonal = [1, 2, 3, 4]
matrix = np.diag(values_below_diagonal, k=-1)
print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [23]:
import numpy as np
checkerboard_matrix = np.zeros((8, 8), dtype=int)
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1
print(checkerboard_matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [24]:
import numpy as np
shape = (6, 7, 8)
flat_index = 100
indices_xyz = np.unravel_index(flat_index, shape)
print("Index (x, y, z) of the 100th element:", indices_xyz)


Index (x, y, z) of the 100th element: (1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [25]:
import numpy as np
checkerboard_tile = np.array([[0, 1], [1, 0]])
checkerboard_matrix = np.tile(checkerboard_tile, (4, 4))
print(checkerboard_matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [26]:
import numpy as np
random_matrix = np.random.rand(5, 5)
mean_value = np.mean(random_matrix)
std_deviation = np.std(random_matrix)
normalized_matrix = (random_matrix - mean_value) / std_deviation
print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.37290164 0.2535003  0.1784222  0.77403142 0.15629097]
 [0.0211089  0.91813386 0.40779438 0.73114245 0.50911022]
 [0.56172366 0.27828204 0.21910175 0.05753985 0.28536275]
 [0.59596035 0.21675111 0.25596973 0.47646371 0.48779463]
 [0.92914795 0.13452206 0.99196069 0.30959537 0.11311969]]

Normalized Matrix:
[[-0.13236845 -0.56505385 -0.83712111  1.32124164 -0.91732003]
 [-1.40719146  1.84343864 -0.0059245   1.16582103  0.36122286]
 [ 0.5518829  -0.47525001 -0.68970695 -1.27517336 -0.44959102]
 [ 0.67594948 -0.69822518 -0.55610513  0.24291876  0.28397962]
 [ 1.88335137 -0.99620601  2.11097156 -0.3617771  -1.07376369]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [27]:
import numpy as np
rgba_dtype = np.dtype([('red', np.uint8),
                       ('green', np.uint8),
                       ('blue', np.uint8),
                       ('alpha', np.uint8)])
color_array = np.array([(255, 0, 0, 255),
                        (0, 255, 0, 255),
                        (0, 0, 255, 255)],
                       dtype=rgba_dtype)
print(color_array)


[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [28]:

matrix_a = np.random.rand(5, 3)
matrix_b = np.random.rand(3, 2)
result_matrix = np.dot(matrix_a, matrix_b)
print("Matrix A (5x3):")
print(matrix_a)
print("\nMatrix B (3x2):")
print(matrix_b)
print("\nResult Matrix (5x2):")
print(result_matrix)


Matrix A (5x3):
[[0.92083931 0.61025332 0.04418471]
 [0.8987463  0.19424592 0.75570213]
 [0.56428806 0.63514191 0.54620274]
 [0.95878412 0.64905738 0.17572602]
 [0.87383724 0.35926859 0.50169433]]

Matrix B (3x2):
[[0.81434613 0.68872215]
 [0.96733516 0.30041225]
 [0.87171766 0.39474967]]

Result Matrix (5x2):
[[1.37871801 0.8349719 ]
 [1.57855037 0.9756535 ]
 [1.55005547 0.79505545]
 [1.56182164 0.92468843]
 [1.49647492 0.90780342]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [29]:
import numpy as np
arr = np.array([1, 5, 4, 9, 2, 6, 7, 3, 8, 10])
arr[(arr > 3) & (arr < 8)] *= -1
print("Modified Array:")
print(arr)


Modified Array:
[ 1 -5 -4  9  2 -6 -7  3  8 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [30]:

print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [32]:

#every expression is legal without last expression

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [34]:
import numpy as np
result1 = np.array(0) / np.array(0)
print(result1)

# result2 = np.array(0) // np.array(0)

result3 = np.array([np.nan]).astype(int).astype(float)
print(result3)


nan
[-9.22337204e+18]


<ipython-input-34-fc72f554b21d>:2: RuntimeWarning: invalid value encountered in divide
  result1 = np.array(0) / np.array(0)


#### 29. How to round away from zero a float array ? (★☆☆)

In [35]:
import numpy as np
float_array = np.array([-3.14, -2.5, -1.8, 0.5, 1.2, 2.7, 3.8])
rounded_array = np.where(float_array < 0, np.floor(float_array), np.ceil(float_array))
print("Original Float Array:")
print(float_array)
print("\nRounded Array (away from zero):")
print(rounded_array)


Original Float Array:
[-3.14 -2.5  -1.8   0.5   1.2   2.7   3.8 ]

Rounded Array (away from zero):
[-4. -3. -2.  1.  2.  3.  4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [36]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
common_values = np.intersect1d(array1, array2)
print("Array 1:", array1)
print("Array 2:", array2)
print("Common Values:", common_values)


Array 1: [1 2 3 4 5]
Array 2: [3 4 5 6 7]
Common Values: [3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
import numpy as np
np.seterr(all='ignore')
np.seterr(all='warn')


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [37]:
result = np.sqrt(-1) == np.emath.sqrt(-1)
print(result)


False


<ipython-input-37-2ef11ef0a6f2>:1: RuntimeWarning: invalid value encountered in sqrt
  result = np.sqrt(-1) == np.emath.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [38]:
from datetime import datetime, timedelta
today = datetime.now().date()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2023-12-18
Today: 2023-12-19
Tomorrow: 2023-12-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [39]:
from datetime import datetime, timedelta
start_date = datetime(2016, 7, 1)
num_days_in_july = 31
all_dates = [start_date + timedelta(days=i) for i in range(num_days_in_july)]
for date in all_dates:
    print(date)


2016-07-01 00:00:00
2016-07-02 00:00:00
2016-07-03 00:00:00
2016-07-04 00:00:00
2016-07-05 00:00:00
2016-07-06 00:00:00
2016-07-07 00:00:00
2016-07-08 00:00:00
2016-07-09 00:00:00
2016-07-10 00:00:00
2016-07-11 00:00:00
2016-07-12 00:00:00
2016-07-13 00:00:00
2016-07-14 00:00:00
2016-07-15 00:00:00
2016-07-16 00:00:00
2016-07-17 00:00:00
2016-07-18 00:00:00
2016-07-19 00:00:00
2016-07-20 00:00:00
2016-07-21 00:00:00
2016-07-22 00:00:00
2016-07-23 00:00:00
2016-07-24 00:00:00
2016-07-25 00:00:00
2016-07-26 00:00:00
2016-07-27 00:00:00
2016-07-28 00:00:00
2016-07-29 00:00:00
2016-07-30 00:00:00
2016-07-31 00:00:00


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [42]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
A = A.astype(float)
A += B
A *= -0.5
result = A
print("Result:", result)


Result: [-2.5 -3.5 -4.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [43]:

integer_part_direct = random_array.astype(int)
print("\nMethod 4 - Direct Conversion:")
print(integer_part_direct)



Method 4 - Direct Conversion:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [44]:
import numpy as np
matrix = np.tile(np.arange(5), (5, 1))

print(matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [45]:

def generate_integers():
    for i in range(10):
        yield i
generated_array = np.fromiter(generate_integers(), dtype=int)

print("Generated Array:", generated_array)


Generated Array: [0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [46]:

vector = np.linspace(0, 1, 12)[1:-1]
print("Vector:", vector)


Vector: [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [47]:
import numpy as np
random_vector = np.random.rand(10)
sorted_vector = np.sort(random_vector)
print("Random Vector:", random_vector)
print("Sorted Vector:", sorted_vector)


Random Vector: [0.50104985 0.52733423 0.94080896 0.13339166 0.16945032 0.36493341
 0.01658464 0.10270526 0.72285664 0.65333644]
Sorted Vector: [0.01658464 0.10270526 0.13339166 0.16945032 0.36493341 0.50104985
 0.52733423 0.65333644 0.72285664 0.94080896]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)