### Questions 1

Create a matrix of 5x5 with random integers, after that swap its first and last rows.

In [ ]:
import numpy as np
array=np.random.randint(1,30,25).reshape((5,5))
print(" Orginal array: \n",array)
array[:1,:],array[4::,:]=array[4::,:].copy(),array[:1].copy()
print(" \nSwaped array: \n",array)


 Orginal array: 
 [[ 7 17 18  4 16]
 [13  4 11 14  5]
 [14 10  4 21 23]
 [ 6 27  6  6 24]
 [ 1 15 24 24  5]]
 
Swaped array: 
 [[ 1 15 24 24  5]
 [13  4 11 14  5]
 [14 10  4 21 23]
 [ 6 27  6  6 24]
 [ 7 17 18  4 16]]


### Question 2

Create a 2D array, remove all rows that contain at least one zero.

In [ ]:
import numpy as np
array=np.random.randint(-5,5,25).reshape(5,5)
print("Orginal Array\n",array)
nonarray=np.all(array!=0,axis=0)
array=array[nonarray]

print("\nAfter arrray\n",array)


Orginal Array
 [[-5  3 -2 -3  0]
 [ 2 -1  1 -4  3]
 [ 2 -5  0 -2  2]
 [ 2  3  3  2  4]
 [ 2  0 -4  0 -4]]

After arrray
 [[-5  3 -2 -3  0]]


### Question 3

Write a NumPy program to find the real and imaginary parts of an array of complex numbers.<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]

In [75]:
import numpy as np
def real_imag(arr):
    real_part = arr + 0 - arr.imag
    imag_part = arr.real

    return real_part, imag_part

original_array = np.array([1.00000000 + 0.j, 0.70710678 + 0.70710678j])

# Finding real and imaginary parts using custom function
real_parts, imag_parts = real_imag(original_array)

# Displaying the results
print("Original array:", original_array)
print("Real parts:", real_parts)
print("Imaginary parts:", imag_parts)


Original array: [1.        +0.j         0.70710678+0.70710678j]
Real parts: [1.+0.j         0.+0.70710678j]
Imaginary parts: [1.         0.70710678]


### Question 4

Write a NumPy program to remove the duplicate elements of an array.<br>
Original array:
[10 10 20 20 30 30]


In [ ]:
import numpy as np
array = np.array([10,10,20,20,30,30])
removed=np.unique(array)
removed

array([10, 20, 30])

### Question 5

Write a NumPy program to create a 3x3x3 array with random values.

In [ ]:
import numpy as np
array=np.random.randint(1,30,27).reshape((3,3,3))
array

array([[[23, 28, 26],
        [ 6, 28, 24],
        [ 2, 22, 28]],

       [[15, 13,  2],
        [23,  8, 15],
        [18, 12,  1]],

       [[26, 26, 27],
        [ 8, 26, 18],
        [23,  9, 19]]])

### Question 6

Write a NumPy program to create a random vector of size 10 and sort it.
<b>Note:<\b> Do not use builtin sorting function

In [ ]:
array=np.random.randint(1,20,10)
for i in range(10):
    for j in range(9):
        if array[j] > array[j + 1]:
            temp = array[j]
            array[j] = array[j + 1]
            array[j + 1] = temp

print("\nArray after sorted:", array)




Array after sorted: [ 3  3  8  8  8 10 12 12 16 16]


### Question 7

Write a NumPy program to check two random arrays are equal or not.

In [ ]:
array1=np.array([1,2,3,4,5])
array2=np.array([1,2,3,4,5])
result=np.array_equal(array1,array2)
result

True

### Question 8

Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.<br>

Original array:<br>
[[10 40]<br>
[30 20]]

In [ ]:
import numpy as np
original_array = np.array([[10, 40],
                           [30, 20]])
sorted_axis0 = np.sort(original_array, axis=0)
sorted_last_axis = np.sort(original_array, axis=-1)
sorted_flattened = np.sort(original_array.flatten())
print(original_array)
print(sorted_axis0)
print(sorted_last_axis)
print(sorted_flattened)


[[10 40]
 [30 20]]
[[10 20]
 [30 40]]
[[10 40]
 [20 30]]
[10 20 30 40]


### Question 9

Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.<br>

Original array:<br>
[-1.6 -1.5 -0.3 0.1 1.4 1.8 2. ]

In [ ]:
import numpy as np
original_array = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.])
floor_values = np.floor(original_array)
ceiling_values = np.ceil(original_array)
truncated_values = np.trunc(original_array)

print("Original array:")
print(original_array)

print("\nFloor values:")
print(floor_values)

print("\nCeiling values:")
print(ceiling_values)

print("\nTruncated values:")
print(truncated_values)


Original array:
[-1.6 -1.5 -0.3  0.1  1.4  1.8  2. ]

Floor values:
[-2. -2. -1.  0.  1.  1.  2.]

Ceiling values:
[-1. -1. -0.  1.  2.  2.  2.]

Truncated values:
[-1. -1. -0.  0.  1.  1.  2.]


### Questions 10

Write a NumPy program to display all the dates for the month of March, 2017

In [ ]:
from datetime import datetime,timedelta
start=datetime(2017,3,1)
dates=[start+timedelta(days=i) for i in range(31)]
for i in dates:
  print(i)


2017-03-01 00:00:00
2017-03-02 00:00:00
2017-03-03 00:00:00
2017-03-04 00:00:00
2017-03-05 00:00:00
2017-03-06 00:00:00
2017-03-07 00:00:00
2017-03-08 00:00:00
2017-03-09 00:00:00
2017-03-10 00:00:00
2017-03-11 00:00:00
2017-03-12 00:00:00
2017-03-13 00:00:00
2017-03-14 00:00:00
2017-03-15 00:00:00
2017-03-16 00:00:00
2017-03-17 00:00:00
2017-03-18 00:00:00
2017-03-19 00:00:00
2017-03-20 00:00:00
2017-03-21 00:00:00
2017-03-22 00:00:00
2017-03-23 00:00:00
2017-03-24 00:00:00
2017-03-25 00:00:00
2017-03-26 00:00:00
2017-03-27 00:00:00
2017-03-28 00:00:00
2017-03-29 00:00:00
2017-03-30 00:00:00
2017-03-31 00:00:00


### Question 11

Write a NumPy program to create 24 python datetime.datetime objects (single object for every hour), and then put it in a numpy array.

In [ ]:
import numpy as np
from datetime import datetime, timedelta
start_time = datetime(2023, 1, 1, 0, 0, 0)
datetime_objects = [start_time + timedelta(hours=i) for i in range(24)]
datetime_array = np.array(datetime_objects)
print("NumPy array of datetime objects:")
print(datetime_array)


NumPy array of datetime objects:
[datetime.datetime(2023, 1, 1, 0, 0) datetime.datetime(2023, 1, 1, 1, 0)
 datetime.datetime(2023, 1, 1, 2, 0) datetime.datetime(2023, 1, 1, 3, 0)
 datetime.datetime(2023, 1, 1, 4, 0) datetime.datetime(2023, 1, 1, 5, 0)
 datetime.datetime(2023, 1, 1, 6, 0) datetime.datetime(2023, 1, 1, 7, 0)
 datetime.datetime(2023, 1, 1, 8, 0) datetime.datetime(2023, 1, 1, 9, 0)
 datetime.datetime(2023, 1, 1, 10, 0) datetime.datetime(2023, 1, 1, 11, 0)
 datetime.datetime(2023, 1, 1, 12, 0) datetime.datetime(2023, 1, 1, 13, 0)
 datetime.datetime(2023, 1, 1, 14, 0) datetime.datetime(2023, 1, 1, 15, 0)
 datetime.datetime(2023, 1, 1, 16, 0) datetime.datetime(2023, 1, 1, 17, 0)
 datetime.datetime(2023, 1, 1, 18, 0) datetime.datetime(2023, 1, 1, 19, 0)
 datetime.datetime(2023, 1, 1, 20, 0) datetime.datetime(2023, 1, 1, 21, 0)
 datetime.datetime(2023, 1, 1, 22, 0) datetime.datetime(2023, 1, 1, 23, 0)]


### Question 12

Write a NumPy program to concatenate element-wise two arrays of string.<br>
<b>Example <\b>
Array1:<br>
['Python' 'PHP']<br>
Array2:<br>
[' Java' ' C++']<br>
new array:<br>
['Python Java' 'PHP C++']<br>

In [ ]:
import numpy as np
array1 = np.array(['Python', 'PHP'])
array2 = np.array([' Java', ' C++'])
result_array = np.core.defchararray.add(array1, array2)
print("Array1:")
print(array1)
print("Array2:")
print(array2)
print("Concatenated array:")
print(result_array)


Array1:
['Python' 'PHP']
Array2:
[' Java' ' C++']
Concatenated array:
['Python Java' 'PHP C++']
